# Transformacja danych - March Madness 2026

**Output:** `m_data.csv` i `w_data.csv`

In [1]:
import pandas as pd
from pathlib import Path

path = Path("data/")

In [2]:
m_tourney = pd.read_csv("data/MNCAATourneyDetailedResults.csv")
w_tourney = pd.read_csv("data/WNCAATourneyDetailedResults.csv")
m_seeds = pd.read_csv("data/MNCAATourneySeeds.csv")
w_seeds = pd.read_csv("data/WNCAATourneySeeds.csv")
m_regular = pd.read_csv("data/MRegularSeasonDetailedResults.csv")
w_regular = pd.read_csv("data/WRegularSeasonDetailedResults.csv")

## Mężczyźni

In [3]:
m_tourney["isTourney"] = 1
m_regular["isTourney"] = 0

m_tourney_regular = pd.concat([m_tourney, m_regular], ignore_index=True)

m_data = (
    m_tourney_regular
    .merge(m_seeds, left_on=["Season", "WTeamID"], right_on=["Season", "TeamID"], how="left")
    .rename(columns={"Seed": "WSeed"})
    .drop(columns=["TeamID"])
    .merge(m_seeds, left_on=["Season", "LTeamID"], right_on=["Season", "TeamID"], how="left")
    .rename(columns={"Seed": "LSeed"})
    .drop(columns=["TeamID"])
)

m_data.loc[m_data["isTourney"] == 0, ["WSeed", "LSeed"]] = pd.NA

print(f"m_data shape: {m_data.shape}")
m_data.head()

m_data shape: (125480, 37)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,isTourney,WSeed,LSeed
0,2003,134,1421,92,1411,84,N,1,32,69,...,17,28,16,15,5,0,22,1,X16b,X16a
1,2003,136,1112,80,1436,51,N,0,31,66,...,8,26,12,17,10,3,15,1,Z01,Z16
2,2003,136,1113,84,1272,71,N,0,31,59,...,20,22,11,12,2,5,18,1,Z10,Z07
3,2003,136,1141,79,1166,73,N,0,29,53,...,14,17,20,21,6,6,21,1,Z11,Z06
4,2003,136,1143,76,1301,74,N,1,27,64,...,10,26,16,14,5,8,19,1,W08,W09

## Kobiety

In [4]:
w_tourney["isTourney"] = 1
w_regular["isTourney"] = 0

w_tourney_regular = pd.concat([w_tourney, w_regular], ignore_index=True)

w_data = (
    w_tourney_regular
    .merge(w_seeds, left_on=["Season", "WTeamID"], right_on=["Season", "TeamID"], how="left")
    .rename(columns={"Seed": "WSeed"})
    .drop(columns=["TeamID"])
    .merge(w_seeds, left_on=["Season", "LTeamID"], right_on=["Season", "TeamID"], how="left")
    .rename(columns={"Seed": "LSeed"})
    .drop(columns=["TeamID"])
)

w_data.loc[w_data["isTourney"] == 0, ["WSeed", "LSeed"]] = pd.NA

print(f"w_data shape: {w_data.shape}")
w_data.head()

w_data shape: (87734, 37)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,isTourney,WSeed,LSeed
0,2010,138,3124,69,3201,55,N,0,28,57,...,17,19,12,18,4,1,18,1,X04,X13
1,2010,138,3173,67,3395,66,N,0,23,59,...,18,26,8,8,8,6,22,1,X08,X09
2,2010,138,3181,72,3214,37,H,0,26,57,...,10,21,4,16,6,4,20,1,X02,X15
3,2010,138,3199,75,3256,61,H,0,25,63,...,16,21,13,16,5,4,24,1,W03,W14
4,2010,138,3207,62,3265,42,N,0,24,68,...,16,22,9,10,3,4,12,1,X05,X12

In [5]:
m_data.to_csv("data/m_data.csv", index=False)
w_data.to_csv("data/w_data.csv", index=False)