In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt

In [3]:
season_features_m = pd.read_csv('season_features_m.csv')
season_features_w = pd.read_csv('season_features_w.csv')

In [10]:
seeds_m = pd.read_csv('useful_data/MNCAATourneySeeds.csv')
seeds_w = pd.read_csv('useful_data/WNCAATourneySeeds.csv')

tourney_m = pd.read_csv('useful_data/MNCAATourneyDetailedResults.csv')
tourney_w = pd.read_csv('useful_data/WNCAATourneyDetailedResults.csv')

In [6]:
season_features_m

,Season,TeamID,total_games,wins,win_percentage,avg_points_diff,avg_points_scored,avg_points_allowed,median_points_diff,close_game_winrate,...,neutral_games,home_wins,away_wins,neutral_wins,net_rating_last5,net_rating_last10,recent_elo,recent_elo_mov,neutral_point_diff_smothered,neutral_win_pct_smothered
0,2003,1102,28,12,0.428571,0.250000,57.250000,57.000000,-3.0,0.375000,...,2,9,3,0,-0.082250,-0.169925,1464.057049,1431.869495,-5.846154,1.153846
1,2003,1103,27,13,0.481481,0.629630,78.777778,78.148148,-2.0,0.500000,...,0,9,4,0,0.047365,0.012982,1489.794330,1486.096852,0.868132,0.868132
2,2003,1104,28,17,0.607143,4.285714,69.285714,65.000000,6.0,0.166667,...,4,13,1,3,0.055474,-0.000301,1522.779341,1550.124488,4.567901,3.317901
3,2003,1105,26,7,0.269231,-4.884615,71.769231,76.653846,-3.5,0.222222,...,0,5,2,0,-0.018767,-0.005925,1397.458717,1317.724099,-8.880952,-8.880952
4,2003,1106,28,13,0.464286,-0.142857,63.607143,63.750000,-1.0,0.500000,...,2,8,5,0,-0.060571,-0.018401,1477.517856,1438.886060,-5.275510,1.224490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8341,2026,1477,29,9,0.310345,-8.827586,66.931034,75.758621,-8.0,0.500000,...,1,4,4,1,-0.087072,-0.065297,1416.555054,1332.815453,1.479167,-14.520833
8342,2026,1478,30,14,0.466667,-1.300000,72.366667,73.666667,-1.0,0.571429,...,2,8,5,1,0.120231,0.053502,1489.890718,1449.574533,-3.859053,0.140947
8343,2026,1479,29,13,0.448276,-0.620690,68.551724,69.172414,-2.0,0.307692,...,0,8,5,0,-0.077587,-0.034222,1492.056063,1484.430788,2.181818,2.181818
8344,2026,1480,28,12,0.428571,-5.535714,75.142857,80.678571,-3.0,0.500000,...,0,8,4,0,0.030477,-0.021299,1465.061078,1401.650560,-10.292308,-10.292308
8345,2026,1481,28,11,0.392857,-5.964286,61.464286,67.428571,-4.5,0.166667,...,0,6,5,0,0.022530,-0.011780,1461.498663,1407.370823,-11.083333,-11.083333

In [11]:
tourney_m

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444,2025,146,1120,70,1277,64,N,0,26,61,...,23,13,16,13,28,12,9,5,5,18
1445,2025,146,1222,69,1397,50,N,0,28,66,...,29,15,20,12,23,12,9,3,2,9
1446,2025,152,1196,79,1120,73,N,0,25,53,...,25,16,23,9,21,11,14,11,3,22
1447,2025,152,1222,70,1181,67,N,0,23,61,...,17,18,23,10,21,14,7,7,4,16
1448,2025,154,1196,65,1222,63,N,0,21,53,...,25,9,14,15,24,5,9,5,6,19

In [9]:
import pandas as pd

# zakładam, że masz już dwa DataFrame: season_features_m i m_seeds

merged_m = season_features_m.merge(
    seeds_m,
    how='left',          # left join
    on=['Season', 'TeamID']  # kolumny, po których łączymy
)

merged_w = season_features_w.merge(
    seeds_w,
    how='left',          # left join
    on=['Season', 'TeamID']  # kolumny, po których łączymy
)

In [ ]:
# merge dla zwycięzców (WTeamID)
m_tourney_with_win = tourney_m.merge(
    merged_m,
    how='left',
    left_on=['Season', 'WTeamID'],
    right_on=['Season', 'TeamID'],
    suffixes=('', '_w')  # dodajemy "_w" do kolumn z merged, aby rozróżnić
)

# merge dla przegranych (LTeamID)
m_tourney_full = m_tourney_with_win.merge(
    merged_m,
    how='left',
    left_on=['Season', 'LTeamID'],
    right_on=['Season', 'TeamID'],
    suffixes=('', '_l')  # dodajemy "_l" do kolumn z merged, aby rozróżnić
)

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT  WFGM  WFGA  \
0    2003     134     1421      92     1411      84    N      1    32    69
1    2003     136     1112      80     1436      51    N      0    31    66
2    2003     136     1113      84     1272      71    N      0    31    59
3    2003     136     1141      79     1166      73    N      0    29    53
4    2003     136     1143      76     1301      74    N      1    27    64

   ...  home_wins_l  away_wins_l  neutral_wins_l  net_rating_last5_l  \
0  ...           11            4               3            0.144024
1  ...            9            7               3            0.132857
2  ...           14            7               2            0.142614
3  ...           17            7               5            0.139675
4  ...           13            3               2           -0.004743

   net_rating_last10_l  recent_elo_l  recent_elo_mov_l  \
0             0.055013   1523.249387       1483.364423
1             0.116790   1580.083067       1620.788433
2             0.164463   1621.746286       1743.711460
3             0.111507   1656.990512       1765.716591
4            -0.028774   1539.756584       1599.176153

   neutral_point_diff_smothered_l  neutral_win_pct_smothered_l  Seed_l
0                        5.763228                     2.013228    X16a
1                       12.192857                     5.992857     Z16
2                       17.636364                    12.136364     Z07
3                       28.995722                    14.395722     Z06
4                        1.541667                     3.541667     W09

[5 rows x 206 columns]

In [13]:
# merge dla zwycięzców (WTeamID)
w_tourney_with_win = tourney_w.merge(
    merged_w,
    how='left',
    left_on=['Season', 'WTeamID'],
    right_on=['Season', 'TeamID'],
    suffixes=('', '_w')  # dodajemy "_w" do kolumn z merged, aby rozróżnić
)

# merge dla przegranych (LTeamID)
w_tourney_full = w_tourney_with_win.merge(
    merged_w,
    how='left',
    left_on=['Season', 'LTeamID'],
    right_on=['Season', 'TeamID'],
    suffixes=('', '_l')  # dodajemy "_l" do kolumn z merged, aby rozróżnić
)

In [14]:
# zapis do pliku CSV
m_tourney_full.to_csv("m_tourney_full.csv", index=False)
w_tourney_full.to_csv("w_tourney_full.csv", index=False)

In [15]:
# Train: sezony do 2023 włącznie
train_m = m_tourney_full[m_tourney_full['Season'] <= 2023]

# Test: sezon 2024
test_m = m_tourney_full[m_tourney_full['Season'] == 2024]

# Validation: sezon 2025
val_m = m_tourney_full[m_tourney_full['Season'] == 2025]

# opcjonalnie podgląd liczby wier

In [16]:

train_m.to_csv("tourney_train_m.csv", index=False)

test_m.to_csv("tourney_test_m.csv", index=False)

val_m.to_csv("tourney_val_m.csv", index=False)

In [17]:
# Train: sezony do 2023 włącznie
train_w = w_tourney_full[w_tourney_full['Season'] <= 2023]

# Test: sezon 2024
test_w = w_tourney_full[w_tourney_full['Season'] == 2024]

# Validation: sezon 2025
val_w = w_tourney_full[w_tourney_full['Season'] == 2025]

# opcjonalnie podgląd liczby wier

train_w.to_csv("tourney_train_w.csv", index=False)

test_w.to_csv("tourney_test_w.csv", index=False)

val_w.to_csv("tourney_val_w.csv", index=False)